### ISSUE TITLE
Archive Channel using incorrect method and path.

### ISSUE THREAD

**Issue by MartelliAtPythian** [xmatters/xm-labs-slack#1]
Suggest Following change:

exports.archiveChannel = function( channelName, token) {

    var channel = this.getChannel( channelName );
    var channelPath = '/channels.archive?token=' + token + "&channel=" + channel.id
    
    var slackRequest = http.request({
        'endpoint': 'Slack',
        'method': 'POST',
        'path': channelPath
    });
    
    var slackResponse = slackRequest.write();
    var slackBody     = JSON.parse( slackResponse.body );
            
};

Note the suggestion now takes in a token which we found useful to include so that we could leverage the XMatters constants instead of hard-coding in token values to the path, which could change.

**Comment by xMTinkerer** [comment]
Well hey there!
So this library uses the [`Slack` authentication](https://help.xmatters.com/OnDemand/xmodwelcome/integrationbuilder/configure-endpoints.htm#SlackAuthentication), so the token can be retrieved with `http.authenticate( 'Slack' )`. Like so:

```
    var slackRequest = http.request({
        'endpoint': 'Slack',
        'method': 'GET',
        'path': 'api/channels.archive?token=' + http.authenticate( 'Slack' ) + "&channel=" + channel.id
    });
```
With the Slack authentication you use the OAuth flow to retrieve a token and xMatters stores it for you, without the need to have it in a token. Is that something you guys have explored? Do you have a preference to using the constant?

I think we could probably do a test if `token` is passed and use that, otherwise, default back to the `http.authenticate()` call.

**Comment by MartelliAtPythian** [comment]
The authenticate call does not give our team the control we need and did not appear to do anything on our end.

With slack, some functions are only available to a bot user versus a user. Using the constants gives us an easy way to guarantee that the token we want to use is being used for authentication.

**Comment by xMTinkerer** [comment]
Ah yes, good call. I've run into that a couple times and had to make a product change request to get the new permissions. I'll see about making that change. 

If it didn't do anything, then we might need to investigate that as a bug.

**Comment by jonathanrelf** [comment]
The README file still suggests adding the Constant 'Slack Token' but the Slack.js code makes use of the http.authenticate('Slack') token retrieval. This is fine if you're a Slack workspace owner who can complete the authentication approval. I've created a standalone Slack App which has been accepted into my company's Slack instance. Therefore I can follow all the README instructions and retrieve a valid OAuth Token with the appropriate permissions.
Either the JS file needs to change back to referring to the 'Slack Token' constant, or the README advice needs updating to require the Slack Endpoint authentication to be set to 'Slack' when you create the 'Slack' endpoint.

**Comment by xMTinkerer** [comment]
Yuck. You're right. I updated the js file to use the constant per the doc. This is the version we use for demos to potential customers and it uncouples from the Slack auth in the Endpoint screen, which as @MartelliAtPythian mentions, allows for more flexibility. 

Thanks guys.
